# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Screenshot Catalog — macOS .app bundle
# Build with:  bash build_mac.sh

import sys
from pathlib import Path

ROOT = Path(SPECPATH)          # directory containing this .spec file

# ── Source files ──────────────────────────────────────────────────────────────
a = Analysis(
    [str(ROOT / "main.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        # Web UI assets (templates + CSS)
        (str(ROOT / "templates"), "templates"),
        (str(ROOT / "static"),    "static"),
        # Branding
        (str(ROOT / "logo-v2.png"),        "."),
        (str(ROOT / "logo-image.png"),     "."),
        # Default settings (copied to ~/Library/... on first run)
        (str(ROOT / "app_settings.json"),  "."),
    ],
    hiddenimports=[
        # Flask / Werkzeug
        "flask", "flask.templating", "jinja2", "jinja2.ext",
        "werkzeug", "werkzeug.serving", "werkzeug.routing",
        # OCR
        "pytesseract", "PIL", "PIL.Image", "PIL.ImageEnhance", "PIL.ImageFilter",
        # File watching
        "watchdog", "watchdog.observers", "watchdog.events",
        "watchdog.observers.fsevents",   # macOS-specific backend
        # pywebview
        "webview", "webview.platforms", "webview.platforms.cocoa",
        # pyobjc / AppKit (for NSStatusItem)
        "AppKit", "Foundation", "objc", "Foundation.NSOperationQueue",
        # Stdlib
        "sqlite3", "threading", "socket", "subprocess",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "test", "unittest"],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="ScreenshotCatalog",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,          # no Terminal window
    disable_windowed_traceback=False,
    target_arch=None,       # universal2 set in build_mac.sh via --target-arch
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="ScreenshotCatalog",
)

app = BUNDLE(
    coll,
    name="Screenshot Catalog.app",
    icon="ScreenshotCatalog.icns",   # generated by build_mac.sh
    bundle_identifier="com.patrickschroeder.screenshotcatalog",
    info_plist={
        "CFBundleDisplayName":      "Screenshot Catalog",
        "CFBundleShortVersionString": "1.0.0",
        "CFBundleVersion":          "1",
        "NSHighResolutionCapable":  True,
        "LSUIElement":              True,   # hide from Dock (menu-bar-only app)
        "NSAppTransportSecurity":   {"NSAllowsLocalNetworking": True},
    },
)
